### ISSUE TITLE
Add an example of a simple HeistConfig value

### ISSUE THREAD

**Issue by chrissound** [snapframework/heist#101]
So I'm trying to use this library on it's own (without Snap's heist snaplet), but it doesn't appear to be a simple process to create a `HeistConfig` value. Perhaps it would be useful to demonstrate such an example?

**Comment by mightybyte** [comment]
Here are a couple examples of how to create a `HeistConfig`:

https://github.com/snapframework/snap/blob/master/src/Snap/Snaplet/Heist/Internal.hs#L59

https://github.com/snapframework/heist/blob/master/test/suite/Heist/Tutorial/CompiledSplices.lhs#L117

That last link can also be seen in the compiled heist tutorial:

http://snapframework.com/docs/tutorials/compiled-splices

**Comment by chrissound** [comment]
In case this is useful in the future for anyone:
Given a directory of `templates` and a file in that directory with a name of `example.tpl` you can render a template by
```renderTemplate "example" id```
```
renderTemplate :: String -> (HeistState IO -> HeistState IO) -> ActionM ()
renderTemplate fileName hsBinding = do
  let emptyI = return () :: MapSyntax Text (I.Splice IO)
  let emptyC = return () :: MapSyntax Text (HeistCom.Splice IO)
  let emptyA = return () :: MapSyntax Text (AttrSplice IO)
  let templateLocations = [Heist.loadTemplates "templates/"]
  let spliceConfig = SpliceConfig emptyI emptyI emptyC emptyA templateLocations (\_ -> True):: SpliceConfig IO
  heist <- lift $ Heist.initHeist (HeistConfig spliceConfig "" True)
  case heist of
    Right heist' -> do
      rendered <- lift $ I.renderTemplate (hsBinding heist') $ convertString fileName
      case (rendered) of
        Just (builder, _) -> do
          html . convertString $ toLazyByteString builder
        Nothing -> error "heist error"
    Left a -> error . convertString $ show a
```

**Comment by mightybyte** [comment]
Thanks for summarizing an example!  I would like to point out one more thing.  The first 5 `let` statements can be replaced with:

```
let spliceConfig = mempty & hcTemplateLocations .~ [Heist.loadTemplates "templates/"]
```

**Comment by chrissound** [comment]
What modules is & and .~ from?

**Comment by mightybyte** [comment]
[Control.Lens](http://hackage.haskell.org/package/lens-4.15.1/docs/Control-Lens.html) from the [lens package](http://hackage.haskell.org/package/lens).  You can get some pointers in the right direction with [Hayoo](http://hayoo.fh-wedel.de/):

http://hayoo.fh-wedel.de/?query=%28%26%29
http://hayoo.fh-wedel.de/?query=%28.~%29
