### ISSUE TITLE
heist cabal file revision in nixos (and on hackage)?

### ISSUE THREAD

**Issue by gspia** [snapframework/heist#107]
By running 
nix-prefetch-url http://hackage.haskell.org/package/heist-1.0.1.0/revision/6.cabal
I can see the store path to the heist.cabal that, in turn, seems to be old. (The above link seems to show it, too.)

There is aeson upper bound < 1.2 while here on the github it seems to be < 1.3. Also hackage seems to refer to old version, see [heist on hackage](http://hackage.haskell.org/package/heist).

The nixpkgs seems to refer to heist-1.0.1.0 and revision 6. See the lines around line 98640 in
[hackage-packages](https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/development/haskell-modules/hackage-packages.nix).

There is possibly some other revisions/changes made after aeson upper bound change? If so, it would mean that those changes are also not available at nixos.

Any chances to get a new version 1.0.1.1 that would certainly have the latest changes?

**Comment by mightybyte** [comment]
Done.  Thanks for the ping.
