### ISSUE TITLE
This package needs maintenance

### ISSUE THREAD

**Issue by andreasabel** [snapframework/heist#135]
This package is vital for the Haskell ecosystem via the path `hackage-server -> http-io-streams -> heist`.
- https://github.com/haskell-hvr/http-io-streams/pull/7

I am blocked for over three months now by `heist` failing to catch up to GHC 9.2 and `aeson-2`, despite PRs being in place.

I'd love to see a version released that works with the latest Haskell ecosystem.  If you are short on maintainers, please add me (here and on hackage).  Thanks!

**Comment by srid** [comment]
Do we know any alternatives to `heist`? So far, I'm aware of,

- https://github.com/lucasvreis/ondim

**Comment by cydparser** [comment]
I'm handling the next release.

**Comment by andreasabel** [comment]
Great!

The last tag is `1.1.0.1` from 2018 (which is also the latest release on Hackage).
