### ISSUE TITLE
Has anyone forked this so it works with newer ghcs?

### ISSUE THREAD

**Issue by henrylaxen** [snapframework/heist#136]
It looks like the last commit was in Dec. 2020.  There are over 50 forks.  Does anyone have a working version?  Please let me know.
Best wishes,
Henry Laxen

**Comment by srid** [comment]
@henrylaxen See https://github.com/snapframework/heist/pull/130#issuecomment-1086931247

**Comment by cydparser** [comment]
It should build on GHC 9.4.2 now.
