### ISSUE TITLE
Interpreted splices don't work in attributes

### ISSUE THREAD

**Issue by hesselink** [snapframework/heist#30]
If you bind an interpreted splice (e.g. `("foo", textSplice "bar")`) and use it in an attribute, it doesn't work. The following template:

```
<foo/>
<a class="${foo}">bla</a>
```

will render as

```
bar
<a class="${foo}">bla</a>
```

Even nastier, the following template

```
<bind tag=bar><foo/></bind>
<a class="${bar}">bla</a>
```

will render as

```
<a class>bla</a>
```

This is because the bind expands to `<foo/>` at compile time, and heist then takes the text content, which is empty.

The right fix seems to be to compile attributes to Chunks as well, but that looked like a rather invasive fix. Any ideas?

**Comment by mightybyte** [comment]
I'm going to close this for now because I don't see a way around the issue.  Feel free to re-open if you have an implementation you would like considered.
