### ISSUE TITLE
Control.Monad.Except requires mtl-2.2.1

### ISSUE THREAD

**Issue by ChristopherBiscardi** [snapframework/heist#44]
[mtl-2.2.1](https://hackage.haskell.org/package/mtl-2.2.1) has `Except`

Previous versions of [mtl <= 2.2.0.1](https://hackage.haskell.org/package/mtl-2.2.0.1) do not.

[MonadError in Types](https://github.com/snapframework/heist/blob/master/src/Heist/Types.hs#L414) requires Except, and therefore the lower bound of `2.0` currently in Heist is unsuitable.

Currently testing with a [lower bound](https://github.com/snapframework/heist/blob/master/heist.cabal#L156) of `2.2.1` and some [other bounds modifications](https://github.com/snapframework/snap/issues/118) as part of a full Snap app.

**Comment by mightybyte** [comment]
@ChristopherBiscardi I'm going through issues and ran across this one.  Did 047aa39 fix the problem adequately so we can close this out?

**Comment by ChristopherBiscardi** [comment]
@mightybyte Yep, closing. Sorry for the delay.
