### ISSUE TITLE
Heist always in preprocessing mode

### ISSUE THREAD

**Issue by andrewthad** [snapframework/heist#56]
I just noticed this, and I kind of prefer this behavior, but there's no way to switch `HeistState` out of preprocessing mode.

**Comment by andrewthad** [comment]
Sorry. I don't think that I was very clear. When I run `grep -n -r preprocessingMode .` I only see three lines where preprocessing mode is ever mentioned:

    ./heist/src/Heist/Internal/Types/HeistState.hs:202:    , _preprocessingMode   :: Bool
    ./heist/src/Heist/Common.hs:61:    if _preprocessingMode hs
    ./heist/src/Heist.hs:280:                              , _preprocessingMode = True

This indicates that there is no way that it can be set to `False`. I can't see anywhere in the code base where it looks like this is happening.

**Comment by mightybyte** [comment]
It is set to false right here.

https://github.com/snapframework/heist/blob/master/src/Heist.hs#L202

**Comment by andrewthad** [comment]
Thanks. I did not consider the data constructor. That makes more sense.

**Comment by mightybyte** [comment]
Thanks for paying close enough attention to notice the possible issue.
