### ISSUE TITLE
Cannot contain child elements or comments

### ISSUE THREAD

**Issue by andrewthad** [snapframework/heist#57]
I built up a `[Node]` manually using only `xmlhtml`. Let's refer to it as `myNodes`. If I do

    main = BC8.putStrLn $ Blaze.toByteString $ renderXmlFragment UTF8 myNodes

Then it renders fine. But, it is just an XML fragment, so I need to splice this into a template. This seems like it should be simple. It's a constant `[Node]`. So, I tried this:

    main = do
      let heist = hcTemplateLocations  .~ [ loadTemplates "templates" ]
                $ hcNamespace .~ ""
                $ hcCompiledSplices .~ ("report" ## return (yieldPure (nodeSplice (const $ myNodes) ())))
                $ emptyHeistConfig
      heistState <- do
        res <- runEitherT $ initHeist heist
        case res of
          Left err -> error $ unlines err
          Right a -> return a
      builder <- maybe (error "oops") fst $
        renderTemplate heistState "report"
      BC8.putStrLn . Blaze.toByteString $ builder

But now I get this:

    sheets: style:style cannot contain child elements or comments

Which seems bad because it's an exception thrown from pure code in `xmlhtml` (src/Text/XmlHtml/HTML/Render.hs). Also, if I just remove the line for using compiled splices, then it runs fine (but without replacing `<report/>` of course). So, something in heist is messing up the rendering of the otherwise alright node list. In case this is helpful:

Correct rendering of `myNodes`:

    <office:automatic-styles><style:style style:name='basic-column-style' style:family='table-column'><style:table-column-properties fo:break-before='auto' style:column-width='0.9in'/></style:style><style:style style:name='basic-row-style' style:family='table-row'><style:table-row-properties fo:break-before='auto' style:row-height='0.178in' style:use-optimal-row-height='true'/></style:style><style:style style:name='basic-table-style' style:family='table' style:master-page-name='Default'><style:table-properties table:display='true' style:writing-mode='lr-tb'/></style:style><style:style style:name='foo11' style:family='table-cell'><style:table-cell-properties fo:border-top='none' fo:border-bottom='none' fo:border-left='none' fo:border-right='none'/></style:style></office:automatic-styles><office:body><office:spreadsheet><table:table table:name='Sheet1' table:style-name='basic-table-style'><table:table-column table:number-columns-repeated='1' table:style-name='basic-column-style'/><table:table-row table:style-name='basic-row-style'><table:table-cell table:style-name='foo11'><text:p>Hello There</text:p></table:table-cell></table:table-row></table:table></office:spreadsheet></office:body>

report.tpl

    <?xml version="1.0" encoding="UTF-8"?>
    <office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:style="urn:oasis:names:tc:opendocument:xmlns:style:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:meta="urn:oasis:names:tc:opendocument:xmlns:meta:1.0" xmlns:number="urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0" xmlns:presentation="urn:oasis:names:tc:opendocument:xmlns:presentation:1.0" xmlns:svg="urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0" xmlns:chart="urn:oasis:names:tc:opendocument:xmlns:chart:1.0" xmlns:dr3d="urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0" xmlns:math="http://www.w3.org/1998/Math/MathML" xmlns:form="urn:oasis:names:tc:opendocument:xmlns:form:1.0" xmlns:script="urn:oasis:names:tc:opendocument:xmlns:script:1.0" xmlns:ooo="http://openoffice.org/2004/office" xmlns:ooow="http://openoffice.org/2004/writer" xmlns:oooc="http://openoffice.org/2004/calc" xmlns:dom="http://www.w3.org/2001/xml-events" xmlns:xforms="http://www.w3.org/2002/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:rpt="http://openoffice.org/2005/report" xmlns:of="urn:oasis:names:tc:opendocument:xmlns:of:1.2" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:grddl="http://www.w3.org/2003/g/data-view#" xmlns:tableooo="http://openoffice.org/2009/table" xmlns:drawooo="http://openoffice.org/2010/draw" xmlns:calcext="urn:org:documentfoundation:names:experimental:calc:xmlns:calcext:1.0" xmlns:loext="urn:org:documentfoundation:names:experimental:office:xmlns:loext:1.0" xmlns:field="urn:openoffice:names:experimental:ooo-ms-interop:xmlns:field:1.0" xmlns:formx="urn:openoffice:names:experimental:ooxml-odf-interop:xmlns:form:1.0" xmlns:css3t="http://www.w3.org/TR/css3-text/" office:version="1.2">
      <office:scripts/>
      <office:font-face-decls>
        <style:font-face style:name="Liberation Sans" svg:font-family="'Liberation Sans'" style:font-family-generic="swiss" style:font-pitch="variable"/>
        <style:font-face style:name="DejaVu Sans" svg:font-family="'DejaVu Sans'" style:font-family-generic="system" style:font-pitch="variable"/>
        <style:font-face style:name="Droid Sans Fallback" svg:font-family="'Droid Sans Fallback'" style:font-family-generic="system" style:font-pitch="variable"/>
        <style:font-face style:name="FreeSans" svg:font-family="FreeSans" style:font-family-generic="system" style:font-pitch="variable"/>
      </office:font-face-decls>
      <report/>
    </office:document-content>

**Comment by andrewthad** [comment]
Nevermind, just noticed that `nodeSplice` is defined as:

    nodeSplice f = X.renderHtmlFragment X.UTF8 . f

Which means that it doesn't work for XML. Probably worth documenting.

**Comment by mightybyte** [comment]
Ooh, very good catch.  We need two functions, one for XML and one for HTML.  I'll take care of that.

**Comment by mightybyte** [comment]
Ok, the fix is on hackage.
