### ISSUE TITLE
Heist cannot parse "well formed" comments

### ISSUE THREAD

**Issue by eborden** [snapframework/heist#61]
HTML comments have the following format:

```
<!-- foo -->
```

This is fine, however, the number of `-` characters used is not correctly specified in Heist. HTML does not make a distinction between `<!--` and `<!---` or `-->` and `------>`. Any hyphens after the opening two and preceding the ending two are not significant. Heist will throw a parse error in this situation.

**Comment by mightybyte** [comment]
Ahh, good catch!  This is actually an issue in the parser package, xmlhtml.  So I'm opening an issue there: https://github.com/snapframework/xmlhtml/issues/15

**Comment by eborden** [comment]
cool, thanks.
