### ISSUE TITLE
Can't pass-through full JSON object to template

### ISSUE THREAD

**Issue by waldheinz** [snapframework/heist#63]
Maybe I don't understand the point of `bindJson` at all, but I expected the following to be possible:

Bind a JSON splice, for example using:

    bindSplice "foo" (bindJson $ object [ "bar" .= 1, "baz" .= 2 ])

(having `object` and `(.=)` imported from `Data.Aeson`, and then in the template using

    <foo><value/></foo>

but this only produces an error message saying `var` should be specified for `value`. While the docs  say that this is the intended behavior, I do not understand the rationale for this limitation and would like to see it lifted.

**Comment by sopvop** [comment]
Documentation for it sure needs some improvement.
After examining the code I think that <value/> with no var attribute is meant to use only if json is not array or object. It will not encode json object into string.

For example if you bind array of primitive json types, you can use <value/> for its elements.

~~~~.haskell
bindSplice "foo" (bindJson $ object ["vals" .= ["a","b","c"], "bar" .= 1 ])
bindSplice "foo2" (bindJson $ toJson "<div> html shippet</div>")
~~~~
~~~~.xml
<foo>
   <ul>
   <with:vals>
      <li><value/></li>
   </with:vals>
   <!-- alternatively -->
   <with var="vals">
      <li><value/></li>
   </with>
   </ul>

   <value:bar/>
   <value var="bar"/>
</foo>
<foo2>
   <value/>
   <snippet/>
</foo2>
~~~~
Should produce
~~~~.xml
   <ul>
      <li>a</li>
      <li>b</li>
      <li>c</li>

      <li>a</li>
      <li>b</li>
      <li>c</li>
   </ul>
   1
   1
&gt;div&lt; html snippet &gt;/div&lt;
<div> html snippet </div>

~~~~

**Comment by mightybyte** [comment]
@waldheinz I don't understand quite what your question is here.  I think @sopvop gave a pretty good overview of how it's supposed to work.  If you still have a question, could you paste the exact template markup you are using and the output markup that you think it should generate?  I'm going to close this issue for now, but if there's something concrete that we're missing I'll be happy to open it again.
