### ISSUE TITLE
Incorrect DOCTYPE for XML documents.

### ISSUE THREAD

**Issue by justindthomas** [snapframework/heist#77]
I built a template for establishing an RSS feed at https://github.com/justindthomas/blog/blob/master/snaplets/heist/templates/rss.xtpl

Despite trying to direct Snap to render that as "application/rss+xml", it insists on removing the ?xml directives and prepending a <!DOCTYPE html> at the top (see https://ser.endipito.us/rss.xml for an example). That breaks all RSS readers that I've tried (and the validator at https://validator.w3.org/feed/ just aborts immediately when the document is pasted in, saying it's a web page, not an RSS feed).

RSS 2.0 specifies that there should/can be no DOCTYPE. Any mechanism for dropping that from the parser should solve this issue. Also refraining from stripping the ?xml directives for xtpl files would be nice.

**Comment by mightybyte** [comment]
Hi, I just pushed a change to the 0.14-stable branch that I think should fix this issue.  Could you try it and let me know if it works for you?

**Comment by justindthomas** [comment]
Hey there - looks great on my local machine (specifying the commit directly in my stack.yaml). The doctype is omitted on the appropriate page.

I don't see a quick way to specify a git dependency in Halcyon, so I'll wait for it to make it's way to the repos to get that updated on my public server.

Thanks!

**Comment by mightybyte** [comment]
I just uploaded a new version to hackage.  Let me know if you experience any more problems.  Thanks for the bug report!
