### ISSUE TITLE
Odd escaping of whitespace if the first thing in a template is a bind-tag

### ISSUE THREAD

**Issue by sol** [snapframework/heist#8]
If the first thing in a template is a bind-tag and that bind tag is followed by a whitespace then, for some reason, the whitespace is replaced by a numeric character reference (e.g. `\n` becomes `&#10;`).  Is this a bug or a feature?

I can supply a test case that demonstrates this behaviour, if that helps.

**Comment by mightybyte** [comment]
This should be fixed as of heist-1.0.0.0
