### ISSUE TITLE
Namespace warning message gets triggered when splice uses are nested in regular tags

### ISSUE THREAD

**Issue by kaol** [snapframework/heist#85]
The namespace warning message gets triggered when the splice uses are not on top level but instead inside regular tags.

I've made a test demonstrating the issue at https://github.com/kaol/heist/tree/overzealous-namespace-warning-test

**Comment by kaol** [comment]
The fix: https://github.com/kaol/heist/tree/overzealous-namespace-warning

**Comment by mightybyte** [comment]
Merged.  This will be in the next hackage release.  I'm not releasing just yet because I want to see if there are any more comments on the other two open issues.  If this still hasn't been released in a week or two, feel free to bug me about it again.

**Comment by mightybyte** [comment]
Just pushed to hackage, so this should be in.
